### ISSUE TITLE
Monster hunts

### ISSUE THREAD

**Issue by joeynenni** [earthiverse/ALClient#10]
For some reason monster kills I get with `alclient` do not go towards the monster hunts I get from Daisy. Is there a way around this?

I am able to have monster kills count when I manually hunt the monsters. Do you know if browser-based bots have this issue by chance?

**Comment by earthiverse** [comment]
You're probably doing something wrong, because I have no issues doing monster hunts. [This](https://github.com/earthiverse/adventureland-bots/blob/master/source/monsterhunt/earthiverse.ts) is the code I use for monster hunts.

Here's some troubleshooting:

1. You need to be in a party to contribute to other character's monster hunt progress.
2. Your character needs to be the monster's target to get credit for the kill. If the monster is targeting another player, but you kill it, that player still gets credit.

**Comment by joeynenni** [comment]
Ok, thanks. I will tinker a bit more. Closing this issue.
