### ISSUE TITLE
Cannot `smartMove` to `goo`

### ISSUE THREAD

**Issue by oliver-cool-beans** [earthiverse/ALClient#29]
Replicate by
`smartMove('goo')`

ERROR ` Cannot read properties of undefined (reading 'id')`
here https://github.com/earthiverse/ALClient/blob/6069928943aaca9259a768d82c760cedec6c5b47/source/Pathfinder.ts#L575
and wherever else `toNode.id` is referenced after

It happens before the `toNode` is undefined here
`getPath` can't seem to find a path for `{ map: 'goobrawl', x: 8, y: -132 }`
https://github.com/earthiverse/ALClient/blob/6069928943aaca9259a768d82c760cedec6c5b47/source/Pathfinder.ts#L571

Can add a null check here, but why has it broken all of a sudden?
Is this just me?

**Comment by earthiverse** [comment]
It broke because `G.maps.goobrawl` no longer has `instance: true`.

`Pathfinder.locateMonster()` now ignores spawns with `spawn.count <= 0` which filters it out.

If the count goes up in a later update, and `goobrawl` remains inaccessible without the `instance` tag coming back, the error may return.
